language: java
jdk:
  - oraclejdk7
cache:
  directories:
  - .cache/intellij/$IJ_BUILD_NUMBER

notifications:
  email:
    - fkorotkov@twitter.com

install: ./scripts/setup-ci-environment.sh

env:
  global:
    - IJ_VERSION="14.1" IJ_BUILD_NUMBER="141.177" OSS_PANTS_HOME=./.cache/intellij/pants
  matrix:
    - IJ_ULTIMATE=false
    - IJ_ULTIMATE=true
    - USE_PANTS_TO_COMPILE=false
    - USE_ISOLATED_STRATEGY=true

script:
  - ./scripts/run-tests-ci.sh
  - ./scripts/run-custom-integration.sh
      -r $OSS_PANTS_HOME
      -t examples/src/scala/org/pantsbuild/example/hello,examples/src/java/org/pantsbuild/example/hello
