language: java
jdk:
  - oraclejdk7
cache:
  directories:
  - .cache/intellij/IC-$IJ_BUILD_NUMBER
  - .cache/intellij/IU-$IJ_BUILD_NUMBER

notifications:
  email:
    - fkorotkov@twitter.com

install: ./scripts/setup-ci-environment.sh

env:
  matrix:
    - IJ_ULTIMATE=false
    - IJ_ULTIMATE=true
    - USE_PANTS_TO_COMPILE=false
    - USE_ISOLATED_STRATEGY=true

script:
  - ./scripts/run-tests-ci.sh
  - ./scripts/run-custom-integration.sh
      -r ./.cache/pants
      -t examples/src/scala/org/pantsbuild/example/hello,examples/src/java/org/pantsbuild/example/hello
